[package]
name = "rofi-totp"
version = "0.1.0"
authors = ["Revath S Kumar <rsk@revathskumar.com>"]

[dependencies]
yaml-rust = "0.4.2"
dirs = "1.0.4"
base32 = "0.4.0"
oath = "0.10.2"
rust-ini = "0.13"
