name: rofi-totp # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: "0.2.0" # just for humans, typically '1.2+git' or '1.3.2'
summary: Two-Factors Authentication / TOTP /  Google Authenticator utility using rofi
description: |
  Utility to generate TOTP using rofi. Inspired by alfred-gauth plugin and support same ini format for config

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  rofi-totp:
    # See 'snapcraft plugins'
    plugin: rust
    source: .
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - rofi
      - xdotool
    after: [desktop-gnome-platform]
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk

    plugin: make
    build-packages:
    - build-essential
    - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform


  

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  totp-files:
    interface: personal-files
    read:
      - $HOME/.gauth
      - $HOME/2fa.yml
    
apps:
  rofi-totp:
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - totp-files
      - gnome-3-28-1804
    command: desktop-launch rofi-totp
